#!/bin/bash

i=0
for f in $(find $1 -maxdepth 1 -type f | sort)  
do
	flag=1
	echo $f
	for j in ${files[*]}
	do
		echo $j $f
		if cmp $j $f;
		then
			echo same
			ln -f $f $j
			let flag=0
		fi
	done
	if [ "$flag" == "1" ]
	then
		echo "hihi $f"
		files[$i]=$f
		i=$(($i+1))
	fi	
done

